### ISSUE TITLE
Стилистика кода

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Cat-energy#12]
https://github.com/Ktyby/Cat-energy/blob/6c38348ddfb6e21189f5a94f944be22ac96bcc58/www/scss/blocks/nav.scss#L1-L53
Странно, что где-то ты делаешь отступы между логическими элементами стилей (ну там размеры, флексы, шрифты), а где-то нет. Придерживайся одного стиля кода

**Comment by Ktyby** [comment]
changed
