### ISSUE TITLE
Дублирование кода

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Cat-energy#13]
https://github.com/Ktyby/Cat-energy/blob/6c38348ddfb6e21189f5a94f944be22ac96bcc58/www/scss/blocks/nav.scss#L13-L52
Нахера ты здесь дублируешь один и тот же код в модификаторах, если у тебя различия ну максимум в одно-два свойства? Все основные стили, общие для элемента, прописывай в элементе, а в модификаторах указывай только отличия. Ну и не забудь убрать эти модификаторы нахер, я уже писал ^_^

**Comment by Ktyby** [comment]
removed
