### ISSUE TITLE
Язык в alt

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Cat-energy#15]
https://github.com/Ktyby/Cat-energy/blob/6c38348ddfb6e21189f5a94f944be22ac96bcc58/www/index.html#L15

Сайт на русском языке. Не все знают английский. Значит alt (один из атрибутов веб-доступности, между прочим) должен быть на русском. Ну вот как слепой человек, не знающий английского, поймет, что на картинке?)
А вот комменты, коммиты можешь писать по-английски, молодец, это полезно для тебя)

**Comment by Ktyby** [comment]
Changed the language to Russian.
