### ISSUE TITLE
кнопка закрытия

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Cat-energy#21]
пока у тебя нет js - кнопки тоже не должно быть
![image](https://user-images.githubusercontent.com/40032777/72087866-3b94df80-331a-11ea-9d8e-e8577ba12b6f.png)

**Comment by Ktyby** [comment]
Зачем её убирать, если js будет?

**Comment by kirillgenets** [comment]
В критериях сказано, что если нет js - нет кнопки. Сейчас js нет. Можешь просто ее скрыть
