### ISSUE TITLE
Списки

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Cat-energy#3]
https://github.com/Ktyby/Cat-energy/blob/6c38348ddfb6e21189f5a94f944be22ac96bcc58/www/index.html#L13-L23
1. Зачем здесь список? 
2. Как разработчик, читающий твой код, поймет, чем отличается logo и logo_header (кстати, тут не по БЭМ модификатор, тоже косяк)
Совет: это все одно лого и просто один файлик svg (насчет svg, кстати, сказано в критерии, а у тебя какого-то хера png)

**Comment by Ktyby** [comment]
chanched
