### ISSUE TITLE
Лишний стиль

### ISSUE THREAD

**Issue by kirillgenets** [Ktyby/Cat-energy#9]
https://github.com/Ktyby/Cat-energy/blob/6c38348ddfb6e21189f5a94f944be22ac96bcc58/www/scss/blocks/global.scss#L18-L19
Насколько я знаю, это автоматически отменяется нормалайзом, так что стиль лишний

**Comment by Ktyby** [comment]
removed

**Comment by Ktyby** [comment]
removed
